import '../models/alphabet.dart';

/// The alphabet charts, one per course.
///
/// Held in Dart rather than JSON because this is reference data that changes
/// only when a language does — there is no authoring pipeline behind it, and
/// keeping it in code means the IPA is type-checked alongside everything
/// else rather than failing at runtime on a typo.
///
/// The IPA describes the letter *name* as recited, since that is what the
/// screen speaks aloud. Regional variation is real and this picks the
/// standard taught to learners: peninsular Spanish distinguishes /θ/, Latin
/// American Spanish does not, and the two courses differ accordingly.
abstract final class AlphabetData {
  /// The chart for [courseId], or null for a course with none authored.
  ///
  /// Returning null rather than an empty chart lets the UI hide the entry
  /// point entirely instead of offering a blank screen.
  static Alphabet? forCourse(String courseId) => _byCourse[courseId];

  static bool hasChart(String courseId) => _byCourse.containsKey(courseId);

  static final Map<String, Alphabet> _byCourse = {
    'spanish_en': _spanish(dialect: _SpanishDialect.peninsular),
    'spanish_latam_en': _spanish(dialect: _SpanishDialect.latam),
    'french_en': _french,
    'portuguese_en': _portuguese(languageCode: 'pt-PT'),
    'portuguese_br_en': _portuguese(languageCode: 'pt-BR'),
    'dutch_en': _dutch,
    'japanese_en': _japanese,
    'chinese_en': _chinese,
  };

  // ---------------------------------------------------------------- Spanish

  static Alphabet _spanish({required _SpanishDialect dialect}) {
    final isLatam = dialect == _SpanishDialect.latam;
    // The one systematic difference a beginner meets: C before E/I and Z are
    // /θ/ in Spain and /s/ across Latin America. It changes the letter names
    // themselves ("ceta" vs "seta"), so it cannot be a footnote.
    final ceIpa = isLatam ? '/se/' : '/θe/';
    final zetaIpa = isLatam ? '/ˈse.ta/' : '/ˈθe.ta/';
    final cSound = isLatam
        ? 'Like "k" before A/O/U; like "s" before E/I'
        : 'Like "k" before A/O/U; like "th" in "think" before E/I';
    final zSound = isLatam ? 'Like "s" in "sun"' : 'Like "th" in "think"';

    return Alphabet(
      languageCode: isLatam ? 'es-419' : 'es-ES',
      note: isLatam
          ? 'Spanish spelling is almost perfectly regular — once you know '
              'the five vowels, you can read any word aloud. Latin American '
              'Spanish pronounces C (before E/I) and Z as "s".'
          : 'Spanish spelling is almost perfectly regular — once you know '
              'the five vowels, you can read any word aloud.',
      sections: [
        const AlphabetSection(
          title: 'The five vowels',
          subtitle: 'Always these sounds, in every word. Learn these first.',
          letters: [
            LetterSound(
              letter: 'A',
              name: 'a',
              ipa: '/a/',
              soundHint: 'Like "a" in "father"',
              example: 'casa',
              exampleMeaning: 'house',
            ),
            LetterSound(
              letter: 'E',
              name: 'e',
              ipa: '/e/',
              soundHint: 'Like "e" in "bet"',
              example: 'mesa',
              exampleMeaning: 'table',
            ),
            LetterSound(
              letter: 'I',
              name: 'i',
              ipa: '/i/',
              soundHint: 'Like "ee" in "see"',
              example: 'sí',
              exampleMeaning: 'yes',
            ),
            LetterSound(
              letter: 'O',
              name: 'o',
              ipa: '/o/',
              soundHint: 'Like "o" in "more"',
              example: 'ojo',
              exampleMeaning: 'eye',
            ),
            LetterSound(
              letter: 'U',
              name: 'u',
              ipa: '/u/',
              soundHint: 'Like "oo" in "moon"',
              example: 'luna',
              exampleMeaning: 'moon',
            ),
          ],
        ),
        AlphabetSection(
          title: 'Consonants',
          letters: [
            const LetterSound(
              letter: 'B',
              name: 'be',
              ipa: '/be/',
              soundHint: 'Softer than English "b", lips barely touching',
              example: 'bueno',
              exampleMeaning: 'good',
            ),
            LetterSound(
              letter: 'C',
              name: 'ce',
              ipa: ceIpa,
              soundHint: cSound,
              example: 'casa',
              exampleMeaning: 'house',
            ),
            const LetterSound(
              letter: 'D',
              name: 'de',
              ipa: '/de/',
              soundHint: 'Tongue on the teeth; like "th" in "this" between '
                  'vowels',
              example: 'dedo',
              exampleMeaning: 'finger',
            ),
            const LetterSound(
              letter: 'F',
              name: 'efe',
              ipa: '/ˈe.fe/',
              soundHint: 'Like "f" in "fun"',
              example: 'flor',
              exampleMeaning: 'flower',
            ),
            const LetterSound(
              letter: 'G',
              name: 'ge',
              ipa: '/xe/',
              soundHint: 'Like "g" in "go"; a harsh "h" before E/I',
              example: 'gato',
              exampleMeaning: 'cat',
            ),
            const LetterSound(
              letter: 'H',
              name: 'hache',
              ipa: '/ˈa.tʃe/',
              soundHint: 'Always silent',
              example: 'hola',
              exampleMeaning: 'hello',
              note: 'The only truly silent letter in Spanish.',
            ),
            const LetterSound(
              letter: 'J',
              name: 'jota',
              ipa: '/ˈxo.ta/',
              soundHint: 'Harsh "h", from the back of the throat',
              example: 'jugo',
              exampleMeaning: 'juice',
            ),
            const LetterSound(
              letter: 'K',
              name: 'ka',
              ipa: '/ka/',
              soundHint: 'Like "k" in "kite"',
              example: 'kilo',
              exampleMeaning: 'kilo',
              note: 'Only in words borrowed from other languages.',
            ),
            const LetterSound(
              letter: 'L',
              name: 'ele',
              ipa: '/ˈe.le/',
              soundHint: 'Like "l" in "let"',
              example: 'luna',
              exampleMeaning: 'moon',
            ),
            const LetterSound(
              letter: 'M',
              name: 'eme',
              ipa: '/ˈe.me/',
              soundHint: 'Like "m" in "man"',
              example: 'mano',
              exampleMeaning: 'hand',
            ),
            const LetterSound(
              letter: 'N',
              name: 'ene',
              ipa: '/ˈe.ne/',
              soundHint: 'Like "n" in "no"',
              example: 'nada',
              exampleMeaning: 'nothing',
            ),
            const LetterSound(
              letter: 'Ñ',
              name: 'eñe',
              ipa: '/ˈe.ɲe/',
              soundHint: 'Like "ny" in "canyon"',
              example: 'niño',
              exampleMeaning: 'child',
              note: 'A letter in its own right, not an N with a mark.',
            ),
            const LetterSound(
              letter: 'P',
              name: 'pe',
              ipa: '/pe/',
              soundHint: 'Like "p" in "spin" — no puff of air',
              example: 'pan',
              exampleMeaning: 'bread',
            ),
            const LetterSound(
              letter: 'Q',
              name: 'cu',
              ipa: '/ku/',
              soundHint: 'Like "k"; always written "qu"',
              example: 'queso',
              exampleMeaning: 'cheese',
              note: 'The U in "que" and "qui" is silent.',
            ),
            const LetterSound(
              letter: 'R',
              name: 'ere',
              ipa: '/ˈe.ɾe/',
              soundHint: 'A single tap, like the "dd" in "ladder"',
              example: 'pero',
              exampleMeaning: 'but',
            ),
            const LetterSound(
              letter: 'S',
              name: 'ese',
              ipa: '/ˈe.se/',
              soundHint: 'Like "s" in "sun"',
              example: 'sol',
              exampleMeaning: 'sun',
            ),
            const LetterSound(
              letter: 'T',
              name: 'te',
              ipa: '/te/',
              soundHint: 'Tongue on the teeth, no puff of air',
              example: 'todo',
              exampleMeaning: 'everything',
            ),
            const LetterSound(
              letter: 'V',
              name: 'uve',
              ipa: '/ˈu.be/',
              soundHint: 'Same as B — Spanish does not distinguish them',
              example: 'vaca',
              exampleMeaning: 'cow',
              note: 'B and V sound identical to native speakers.',
            ),
            const LetterSound(
              letter: 'W',
              name: 'uve doble',
              ipa: '/ˈu.be ˈdo.ble/',
              soundHint: 'Like "w" in "water"',
              example: 'wifi',
              exampleMeaning: 'wifi',
              note: 'Only in borrowed words.',
            ),
            const LetterSound(
              letter: 'X',
              name: 'equis',
              ipa: '/ˈe.kis/',
              soundHint: 'Like "ks"; sometimes a harsh "h" in place names',
              example: 'examen',
              exampleMeaning: 'exam',
            ),
            const LetterSound(
              letter: 'Y',
              name: 'ye',
              ipa: '/ʝe/',
              soundHint: 'Like "y" in "yes"',
              example: 'yo',
              exampleMeaning: 'I',
            ),
            LetterSound(
              letter: 'Z',
              name: 'zeta',
              ipa: zetaIpa,
              soundHint: zSound,
              example: 'zapato',
              exampleMeaning: 'shoe',
            ),
          ],
        ),
        const AlphabetSection(
          title: 'Letter pairs',
          subtitle: 'Two letters, one sound.',
          letters: [
            LetterSound(
              letter: 'CH',
              name: 'che',
              ipa: '/tʃe/',
              soundHint: 'Like "ch" in "church"',
              example: 'ocho',
              exampleMeaning: 'eight',
            ),
            LetterSound(
              letter: 'LL',
              name: 'elle',
              ipa: '/ˈe.ʝe/',
              soundHint: 'Like "y" in "yes"',
              example: 'llave',
              exampleMeaning: 'key',
            ),
            LetterSound(
              letter: 'RR',
              name: 'erre',
              ipa: '/ˈe.re/',
              soundHint: 'A rolled R — the trilled one',
              example: 'perro',
              exampleMeaning: 'dog',
              note: '"pero" (but) and "perro" (dog) differ only in this.',
            ),
          ],
        ),
      ],
    );
  }

  // ----------------------------------------------------------------- French

  static const Alphabet _french = Alphabet(
    languageCode: 'fr-FR',
    note: 'French letters are often silent at the end of words. The accents '
        'are not decoration — they change the sound.',
    sections: [
      AlphabetSection(
        title: 'The alphabet',
        letters: [
          LetterSound(
            letter: 'A',
            name: 'a',
            ipa: '/a/',
            soundHint: 'Like "a" in "cat"',
            example: 'ami',
            exampleMeaning: 'friend',
          ),
          LetterSound(
            letter: 'B',
            name: 'bé',
            ipa: '/be/',
            soundHint: 'Like "b" in "bed"',
            example: 'bon',
            exampleMeaning: 'good',
          ),
          LetterSound(
            letter: 'C',
            name: 'cé',
            ipa: '/se/',
            soundHint: 'Like "k"; like "s" before E/I/Y',
            example: 'chat',
            exampleMeaning: 'cat',
          ),
          LetterSound(
            letter: 'D',
            name: 'dé',
            ipa: '/de/',
            soundHint: 'Like "d" in "dog"',
            example: 'deux',
            exampleMeaning: 'two',
          ),
          LetterSound(
            letter: 'E',
            name: 'e',
            ipa: '/ø/',
            soundHint: 'Like "u" in "sup"; often silent at word end',
            example: 'le',
            exampleMeaning: 'the',
          ),
          LetterSound(
            letter: 'F',
            name: 'effe',
            ipa: '/ɛf/',
            soundHint: 'Like "f" in "fun"',
            example: 'faire',
            exampleMeaning: 'to do',
          ),
          LetterSound(
            letter: 'G',
            name: 'gé',
            ipa: '/ʒe/',
            soundHint: 'Like "g" in "go"; like "s" in "measure" before E/I',
            example: 'gare',
            exampleMeaning: 'station',
          ),
          LetterSound(
            letter: 'H',
            name: 'ache',
            ipa: '/aʃ/',
            soundHint: 'Always silent',
            example: 'heure',
            exampleMeaning: 'hour',
          ),
          LetterSound(
            letter: 'I',
            name: 'i',
            ipa: '/i/',
            soundHint: 'Like "ee" in "see"',
            example: 'ici',
            exampleMeaning: 'here',
          ),
          LetterSound(
            letter: 'J',
            name: 'ji',
            ipa: '/ʒi/',
            soundHint: 'Like "s" in "measure"',
            example: 'jour',
            exampleMeaning: 'day',
          ),
          LetterSound(
            letter: 'K',
            name: 'ka',
            ipa: '/ka/',
            soundHint: 'Like "k" in "kite"',
            example: 'kilo',
            exampleMeaning: 'kilo',
            note: 'Rare — mostly borrowed words.',
          ),
          LetterSound(
            letter: 'L',
            name: 'elle',
            ipa: '/ɛl/',
            soundHint: 'Like "l" in "let"',
            example: 'lire',
            exampleMeaning: 'to read',
          ),
          LetterSound(
            letter: 'M',
            name: 'emme',
            ipa: '/ɛm/',
            soundHint: 'Like "m" in "man"',
            example: 'main',
            exampleMeaning: 'hand',
          ),
          LetterSound(
            letter: 'N',
            name: 'enne',
            ipa: '/ɛn/',
            soundHint: 'Like "n"; nasalises the vowel before it',
            example: 'non',
            exampleMeaning: 'no',
          ),
          LetterSound(
            letter: 'O',
            name: 'o',
            ipa: '/o/',
            soundHint: 'Like "o" in "more"',
            example: 'mot',
            exampleMeaning: 'word',
          ),
          LetterSound(
            letter: 'P',
            name: 'pé',
            ipa: '/pe/',
            soundHint: 'Like "p" in "spin"',
            example: 'pain',
            exampleMeaning: 'bread',
          ),
          LetterSound(
            letter: 'Q',
            name: 'ku',
            ipa: '/ky/',
            soundHint: 'Like "k"; written "qu"',
            example: 'qui',
            exampleMeaning: 'who',
          ),
          LetterSound(
            letter: 'R',
            name: 'erre',
            ipa: '/ɛʁ/',
            soundHint: 'From the back of the throat, like gargling',
            example: 'rue',
            exampleMeaning: 'street',
            note: 'The hardest French sound for English speakers.',
          ),
          LetterSound(
            letter: 'S',
            name: 'esse',
            ipa: '/ɛs/',
            soundHint: 'Like "s"; like "z" between vowels',
            example: 'sac',
            exampleMeaning: 'bag',
          ),
          LetterSound(
            letter: 'T',
            name: 'té',
            ipa: '/te/',
            soundHint: 'Like "t" in "stop"',
            example: 'tout',
            exampleMeaning: 'all',
          ),
          LetterSound(
            letter: 'U',
            name: 'u',
            ipa: '/y/',
            soundHint: 'Say "ee" with rounded lips — no English equivalent',
            example: 'tu',
            exampleMeaning: 'you',
            note: 'Distinct from OU. "tu" and "tout" are different words.',
          ),
          LetterSound(
            letter: 'V',
            name: 'vé',
            ipa: '/ve/',
            soundHint: 'Like "v" in "van"',
            example: 'vous',
            exampleMeaning: 'you (formal)',
          ),
          LetterSound(
            letter: 'W',
            name: 'double vé',
            ipa: '/du.blə ve/',
            soundHint: 'Like "v" or "w"',
            example: 'wagon',
            exampleMeaning: 'carriage',
            note: 'Rare — borrowed words only.',
          ),
          LetterSound(
            letter: 'X',
            name: 'ixe',
            ipa: '/iks/',
            soundHint: 'Like "ks"; silent at the end of words',
            example: 'dix',
            exampleMeaning: 'ten',
          ),
          LetterSound(
            letter: 'Y',
            name: 'i grec',
            ipa: '/i ɡʁɛk/',
            soundHint: 'Like "ee" in "see"',
            example: 'yeux',
            exampleMeaning: 'eyes',
          ),
          LetterSound(
            letter: 'Z',
            name: 'zède',
            ipa: '/zɛd/',
            soundHint: 'Like "z" in "zoo"',
            example: 'zéro',
            exampleMeaning: 'zero',
          ),
        ],
      ),
      AlphabetSection(
        title: 'Accents',
        subtitle: 'These change the sound, not just the look.',
        letters: [
          LetterSound(
            letter: 'É',
            name: 'e accent aigu',
            ipa: '/e/',
            soundHint: 'Like "ay" in "day"',
            example: 'été',
            exampleMeaning: 'summer',
          ),
          LetterSound(
            letter: 'È',
            name: 'e accent grave',
            ipa: '/ɛ/',
            soundHint: 'Like "e" in "bet"',
            example: 'père',
            exampleMeaning: 'father',
          ),
          LetterSound(
            letter: 'Ê',
            name: 'e accent circonflexe',
            ipa: '/ɛ/',
            soundHint: 'Like "e" in "bet"; marks a lost S',
            example: 'forêt',
            exampleMeaning: 'forest',
          ),
          LetterSound(
            letter: 'Ç',
            name: 'c cédille',
            ipa: '/se se.dij/',
            soundHint: 'Always "s", never "k"',
            example: 'français',
            exampleMeaning: 'French',
          ),
        ],
      ),
    ],
  );

  // ------------------------------------------------------------- Portuguese

  static Alphabet _portuguese({required String languageCode}) {
    final isBrazilian = languageCode == 'pt-BR';
    return Alphabet(
      languageCode: languageCode,
      note: isBrazilian
          ? 'Brazilian Portuguese is more open and musical than European. '
              'Nasal vowels (ã, õ) are its signature sound.'
          : 'European Portuguese swallows unstressed vowels, which makes it '
              'sound faster than it is. Nasal vowels are its signature sound.',
      sections: [
        AlphabetSection(
          title: 'The alphabet',
          letters: [
            const LetterSound(
              letter: 'A',
              name: 'á',
              ipa: '/a/',
              soundHint: 'Like "a" in "father"',
              example: 'água',
              exampleMeaning: 'water',
            ),
            const LetterSound(
              letter: 'B',
              name: 'bê',
              ipa: '/be/',
              soundHint: 'Like "b" in "bed"',
              example: 'bom',
              exampleMeaning: 'good',
            ),
            const LetterSound(
              letter: 'C',
              name: 'cê',
              ipa: '/se/',
              soundHint: 'Like "k"; like "s" before E/I',
              example: 'casa',
              exampleMeaning: 'house',
            ),
            LetterSound(
              letter: 'D',
              name: 'dê',
              ipa: '/de/',
              soundHint: isBrazilian
                  ? 'Like "d"; like "j" in "jeep" before I or final E'
                  : 'Like "d" in "dog"',
              example: 'dia',
              exampleMeaning: 'day',
            ),
            const LetterSound(
              letter: 'E',
              name: 'é',
              ipa: '/ɛ/',
              soundHint: 'Like "e" in "bet"',
              example: 'ele',
              exampleMeaning: 'he',
            ),
            const LetterSound(
              letter: 'F',
              name: 'efe',
              ipa: '/ˈɛ.fɨ/',
              soundHint: 'Like "f" in "fun"',
              example: 'falar',
              exampleMeaning: 'to speak',
            ),
            const LetterSound(
              letter: 'G',
              name: 'gê',
              ipa: '/ʒe/',
              soundHint: 'Like "g" in "go"; like "s" in "measure" before E/I',
              example: 'gato',
              exampleMeaning: 'cat',
            ),
            const LetterSound(
              letter: 'H',
              name: 'agá',
              ipa: '/aˈɡa/',
              soundHint: 'Always silent',
              example: 'hoje',
              exampleMeaning: 'today',
            ),
            const LetterSound(
              letter: 'I',
              name: 'i',
              ipa: '/i/',
              soundHint: 'Like "ee" in "see"',
              example: 'ilha',
              exampleMeaning: 'island',
            ),
            const LetterSound(
              letter: 'J',
              name: 'jota',
              ipa: '/ˈʒɔ.ta/',
              soundHint: 'Like "s" in "measure"',
              example: 'já',
              exampleMeaning: 'already',
            ),
            const LetterSound(
              letter: 'K',
              name: 'cá',
              ipa: '/ka/',
              soundHint: 'Like "k" in "kite"',
              example: 'kilo',
              exampleMeaning: 'kilo',
              note: 'Borrowed words only.',
            ),
            LetterSound(
              letter: 'L',
              name: 'ele',
              ipa: '/ˈɛ.lɨ/',
              soundHint: isBrazilian
                  ? 'Like "l"; like "w" at the end of a syllable'
                  : 'Like "l" in "let"',
              example: 'livro',
              exampleMeaning: 'book',
            ),
            const LetterSound(
              letter: 'M',
              name: 'eme',
              ipa: '/ˈɛ.mɨ/',
              soundHint: 'Like "m"; nasalises the vowel before it',
              example: 'mão',
              exampleMeaning: 'hand',
            ),
            const LetterSound(
              letter: 'N',
              name: 'ene',
              ipa: '/ˈɛ.nɨ/',
              soundHint: 'Like "n"; nasalises the vowel before it',
              example: 'não',
              exampleMeaning: 'no',
            ),
            const LetterSound(
              letter: 'O',
              name: 'ó',
              ipa: '/ɔ/',
              soundHint: 'Like "o" in "more"',
              example: 'olho',
              exampleMeaning: 'eye',
            ),
            const LetterSound(
              letter: 'P',
              name: 'pê',
              ipa: '/pe/',
              soundHint: 'Like "p" in "spin"',
              example: 'pão',
              exampleMeaning: 'bread',
            ),
            const LetterSound(
              letter: 'Q',
              name: 'quê',
              ipa: '/ke/',
              soundHint: 'Like "k"; written "qu"',
              example: 'que',
              exampleMeaning: 'what',
            ),
            LetterSound(
              letter: 'R',
              name: 'erre',
              ipa: '/ˈɛ.ʁɨ/',
              soundHint: isBrazilian
                  ? 'Like "h" in "hat" at the start of a word'
                  : 'Rolled or guttural at the start of a word',
              example: 'rua',
              exampleMeaning: 'street',
            ),
            LetterSound(
              letter: 'S',
              name: 'esse',
              ipa: '/ˈɛ.sɨ/',
              soundHint: isBrazilian
                  ? 'Like "s"; like "z" between vowels'
                  : 'Like "sh" at the end of a syllable',
              example: 'sol',
              exampleMeaning: 'sun',
            ),
            LetterSound(
              letter: 'T',
              name: 'tê',
              ipa: '/te/',
              soundHint: isBrazilian
                  ? 'Like "t"; like "ch" in "cheese" before I or final E'
                  : 'Like "t" in "stop"',
              example: 'tudo',
              exampleMeaning: 'everything',
            ),
            const LetterSound(
              letter: 'U',
              name: 'u',
              ipa: '/u/',
              soundHint: 'Like "oo" in "moon"',
              example: 'uva',
              exampleMeaning: 'grape',
            ),
            const LetterSound(
              letter: 'V',
              name: 'vê',
              ipa: '/ve/',
              soundHint: 'Like "v" in "van"',
              example: 'ver',
              exampleMeaning: 'to see',
            ),
            const LetterSound(
              letter: 'W',
              name: 'dábliu',
              ipa: '/ˈda.bliw/',
              soundHint: 'Like "v" or "w"',
              example: 'watt',
              exampleMeaning: 'watt',
              note: 'Borrowed words only.',
            ),
            const LetterSound(
              letter: 'X',
              name: 'xis',
              ipa: '/ʃis/',
              soundHint: 'Usually like "sh" in "shoe"',
              example: 'peixe',
              exampleMeaning: 'fish',
            ),
            const LetterSound(
              letter: 'Y',
              name: 'ípsilon',
              ipa: '/ˈip.si.lɔn/',
              soundHint: 'Like "ee" in "see"',
              example: 'yoga',
              exampleMeaning: 'yoga',
              note: 'Borrowed words only.',
            ),
            const LetterSound(
              letter: 'Z',
              name: 'zê',
              ipa: '/ze/',
              soundHint: 'Like "z" in "zoo"',
              example: 'zero',
              exampleMeaning: 'zero',
            ),
          ],
        ),
        const AlphabetSection(
          title: 'Nasal vowels',
          subtitle: 'Let the sound out through your nose. This is the '
              'Portuguese accent.',
          letters: [
            LetterSound(
              letter: 'Ã',
              name: 'a til',
              ipa: '/ɐ̃/',
              soundHint: 'Nasal "a" — like the vowel in French "an"',
              example: 'irmã',
              exampleMeaning: 'sister',
            ),
            LetterSound(
              letter: 'Õ',
              name: 'o til',
              ipa: '/õ/',
              soundHint: 'Nasal "o"',
              example: 'limões',
              exampleMeaning: 'lemons',
            ),
            LetterSound(
              letter: 'ÃO',
              name: 'ão',
              ipa: '/ɐ̃w̃/',
              soundHint: 'Nasal "ow" — the most common Portuguese ending',
              example: 'não',
              exampleMeaning: 'no',
            ),
          ],
        ),
      ],
    );
  }

  // ------------------------------------------------------------------ Dutch

  static const Alphabet _dutch = Alphabet(
    languageCode: 'nl-NL',
    note: 'Dutch has a famously guttural G, and vowel combinations that do '
        'not exist in English. The spelling is regular once you know them.',
    sections: [
      AlphabetSection(
        title: 'The alphabet',
        letters: [
          LetterSound(
            letter: 'A',
            name: 'a',
            ipa: '/aː/',
            soundHint: 'Like "a" in "father"',
            example: 'aap',
            exampleMeaning: 'monkey',
          ),
          LetterSound(
            letter: 'B',
            name: 'be',
            ipa: '/beː/',
            soundHint: 'Like "b"; like "p" at the end of a word',
            example: 'boek',
            exampleMeaning: 'book',
          ),
          LetterSound(
            letter: 'C',
            name: 'ce',
            ipa: '/seː/',
            soundHint: 'Like "k" or "s"',
            example: 'cadeau',
            exampleMeaning: 'gift',
            note: 'Mostly in borrowed words.',
          ),
          LetterSound(
            letter: 'D',
            name: 'de',
            ipa: '/deː/',
            soundHint: 'Like "d"; like "t" at the end of a word',
            example: 'dag',
            exampleMeaning: 'day',
          ),
          LetterSound(
            letter: 'E',
            name: 'e',
            ipa: '/eː/',
            soundHint: 'Like "ay" in "day"; like "uh" when unstressed',
            example: 'een',
            exampleMeaning: 'one',
          ),
          LetterSound(
            letter: 'F',
            name: 'ef',
            ipa: '/ɛf/',
            soundHint: 'Like "f" in "fun"',
            example: 'fiets',
            exampleMeaning: 'bicycle',
          ),
          LetterSound(
            letter: 'G',
            name: 'ge',
            ipa: '/ɣeː/',
            soundHint: 'Harsh, from the back of the throat — like clearing it',
            example: 'goed',
            exampleMeaning: 'good',
            note: 'The signature Dutch sound.',
          ),
          LetterSound(
            letter: 'H',
            name: 'ha',
            ipa: '/ɦaː/',
            soundHint: 'Like "h" in "hat"',
            example: 'huis',
            exampleMeaning: 'house',
          ),
          LetterSound(
            letter: 'I',
            name: 'i',
            ipa: '/i/',
            soundHint: 'Like "i" in "sit"',
            example: 'ik',
            exampleMeaning: 'I',
          ),
          LetterSound(
            letter: 'J',
            name: 'je',
            ipa: '/jeː/',
            soundHint: 'Like "y" in "yes"',
            example: 'ja',
            exampleMeaning: 'yes',
          ),
          LetterSound(
            letter: 'K',
            name: 'ka',
            ipa: '/kaː/',
            soundHint: 'Like "k" in "skin"',
            example: 'kat',
            exampleMeaning: 'cat',
          ),
          LetterSound(
            letter: 'L',
            name: 'el',
            ipa: '/ɛl/',
            soundHint: 'Like "l" in "let"',
            example: 'land',
            exampleMeaning: 'country',
          ),
          LetterSound(
            letter: 'M',
            name: 'em',
            ipa: '/ɛm/',
            soundHint: 'Like "m" in "man"',
            example: 'man',
            exampleMeaning: 'man',
          ),
          LetterSound(
            letter: 'N',
            name: 'en',
            ipa: '/ɛn/',
            soundHint: 'Like "n" in "no"',
            example: 'nee',
            exampleMeaning: 'no',
          ),
          LetterSound(
            letter: 'O',
            name: 'o',
            ipa: '/oː/',
            soundHint: 'Like "o" in "more"',
            example: 'ook',
            exampleMeaning: 'also',
          ),
          LetterSound(
            letter: 'P',
            name: 'pe',
            ipa: '/peː/',
            soundHint: 'Like "p" in "spin"',
            example: 'paard',
            exampleMeaning: 'horse',
          ),
          LetterSound(
            letter: 'Q',
            name: 'ku',
            ipa: '/ky/',
            soundHint: 'Like "k"; written "qu"',
            example: 'quiz',
            exampleMeaning: 'quiz',
            note: 'Rare.',
          ),
          LetterSound(
            letter: 'R',
            name: 'er',
            ipa: '/ɛr/',
            soundHint: 'Rolled or guttural, depending on the region',
            example: 'rood',
            exampleMeaning: 'red',
          ),
          LetterSound(
            letter: 'S',
            name: 'es',
            ipa: '/ɛs/',
            soundHint: 'Like "s" in "sun"',
            example: 'stad',
            exampleMeaning: 'city',
          ),
          LetterSound(
            letter: 'T',
            name: 'te',
            ipa: '/teː/',
            soundHint: 'Like "t" in "stop"',
            example: 'tijd',
            exampleMeaning: 'time',
          ),
          LetterSound(
            letter: 'U',
            name: 'u',
            ipa: '/y/',
            soundHint: 'Say "ee" with rounded lips',
            example: 'uur',
            exampleMeaning: 'hour',
          ),
          LetterSound(
            letter: 'V',
            name: 've',
            ipa: '/veː/',
            soundHint: 'Between "v" and "f"',
            example: 'vader',
            exampleMeaning: 'father',
          ),
          LetterSound(
            letter: 'W',
            name: 'we',
            ipa: '/ʋeː/',
            soundHint: 'Between "v" and "w"',
            example: 'water',
            exampleMeaning: 'water',
          ),
          LetterSound(
            letter: 'X',
            name: 'ix',
            ipa: '/ɪks/',
            soundHint: 'Like "ks"',
            example: 'taxi',
            exampleMeaning: 'taxi',
            note: 'Rare.',
          ),
          LetterSound(
            letter: 'Y',
            name: 'Griekse ij',
            ipa: '/ˈɣrikəsə ɛi/',
            soundHint: 'Like "ee" or "y"',
            example: 'yoghurt',
            exampleMeaning: 'yoghurt',
            note: 'Borrowed words only.',
          ),
          LetterSound(
            letter: 'Z',
            name: 'zet',
            ipa: '/zɛt/',
            soundHint: 'Like "z" in "zoo"',
            example: 'zon',
            exampleMeaning: 'sun',
          ),
        ],
      ),
      AlphabetSection(
        title: 'Vowel pairs',
        subtitle: 'Two letters, one sound — and very common.',
        letters: [
          LetterSound(
            letter: 'IJ',
            name: 'lange ij',
            ipa: '/ɛi/',
            soundHint: 'Like "i" in "mine"',
            example: 'wijn',
            exampleMeaning: 'wine',
            note: 'Treated as a single letter; capitalised as "IJ".',
          ),
          LetterSound(
            letter: 'EI',
            name: 'korte ei',
            ipa: '/ɛi/',
            soundHint: 'Identical to IJ',
            example: 'trein',
            exampleMeaning: 'train',
          ),
          LetterSound(
            letter: 'OE',
            name: 'oe',
            ipa: '/u/',
            soundHint: 'Like "oo" in "moon"',
            example: 'boek',
            exampleMeaning: 'book',
          ),
          LetterSound(
            letter: 'UI',
            name: 'ui',
            ipa: '/œy/',
            soundHint: 'No English equivalent — round your lips and glide',
            example: 'huis',
            exampleMeaning: 'house',
            note: 'The hardest Dutch vowel for English speakers.',
          ),
          LetterSound(
            letter: 'EU',
            name: 'eu',
            ipa: '/ø/',
            soundHint: 'Like "u" in French "peu"',
            example: 'deur',
            exampleMeaning: 'door',
          ),
          LetterSound(
            letter: 'AU',
            name: 'au',
            ipa: '/ɑu/',
            soundHint: 'Like "ow" in "how"',
            example: 'blauw',
            exampleMeaning: 'blue',
          ),
        ],
      ),
    ],
  );

  // --------------------------------------------------------------- Japanese

  static const Alphabet _japanese = Alphabet(
    languageCode: 'ja-JP',
    note: 'Japanese has no alphabet — it has syllables. Each character is a '
        'whole sound, and there are only five vowels. Learn hiragana first: '
        'it writes every Japanese word.',
    sections: [
      AlphabetSection(
        title: 'Vowels',
        subtitle: 'Every other sound is a consonant plus one of these five.',
        letters: [
          LetterSound(
            letter: 'あ',
            name: 'a',
            ipa: '/a/',
            soundHint: 'Like "a" in "father"',
            example: 'あめ',
            exampleMeaning: 'rain',
          ),
          LetterSound(
            letter: 'い',
            name: 'i',
            ipa: '/i/',
            soundHint: 'Like "ee" in "see"',
            example: 'いぬ',
            exampleMeaning: 'dog',
          ),
          LetterSound(
            letter: 'う',
            name: 'u',
            ipa: '/ɯ/',
            soundHint: 'Like "oo" in "moon", lips unrounded',
            example: 'うみ',
            exampleMeaning: 'sea',
          ),
          LetterSound(
            letter: 'え',
            name: 'e',
            ipa: '/e/',
            soundHint: 'Like "e" in "bet"',
            example: 'えき',
            exampleMeaning: 'station',
          ),
          LetterSound(
            letter: 'お',
            name: 'o',
            ipa: '/o/',
            soundHint: 'Like "o" in "more"',
            example: 'おと',
            exampleMeaning: 'sound',
          ),
        ],
      ),
      AlphabetSection(
        title: 'K sounds',
        letters: [
          LetterSound(
            letter: 'か',
            name: 'ka',
            ipa: '/ka/',
            soundHint: 'Like "ca" in "car"',
            example: 'かさ',
            exampleMeaning: 'umbrella',
          ),
          LetterSound(
            letter: 'き',
            name: 'ki',
            ipa: '/ki/',
            soundHint: 'Like "key"',
            example: 'きく',
            exampleMeaning: 'to listen',
          ),
          LetterSound(
            letter: 'く',
            name: 'ku',
            ipa: '/kɯ/',
            soundHint: 'Like "coo"',
            example: 'くち',
            exampleMeaning: 'mouth',
          ),
          LetterSound(
            letter: 'け',
            name: 'ke',
            ipa: '/ke/',
            soundHint: 'Like "ke" in "kettle"',
            example: 'けさ',
            exampleMeaning: 'this morning',
          ),
          LetterSound(
            letter: 'こ',
            name: 'ko',
            ipa: '/ko/',
            soundHint: 'Like "co" in "cold"',
            example: 'ここ',
            exampleMeaning: 'here',
          ),
        ],
      ),
      AlphabetSection(
        title: 'S sounds',
        letters: [
          LetterSound(
            letter: 'さ',
            name: 'sa',
            ipa: '/sa/',
            soundHint: 'Like "sa" in "sock"',
            example: 'さかな',
            exampleMeaning: 'fish',
          ),
          LetterSound(
            letter: 'し',
            name: 'shi',
            ipa: '/ɕi/',
            soundHint: 'Like "she" — not "si"',
            example: 'しろ',
            exampleMeaning: 'white',
            note: 'Irregular: the S row breaks pattern here.',
          ),
          LetterSound(
            letter: 'す',
            name: 'su',
            ipa: '/sɯ/',
            soundHint: 'Like "soo"',
            example: 'すし',
            exampleMeaning: 'sushi',
          ),
          LetterSound(
            letter: 'せ',
            name: 'se',
            ipa: '/se/',
            soundHint: 'Like "se" in "set"',
            example: 'せかい',
            exampleMeaning: 'world',
          ),
          LetterSound(
            letter: 'そ',
            name: 'so',
            ipa: '/so/',
            soundHint: 'Like "so"',
            example: 'そら',
            exampleMeaning: 'sky',
          ),
        ],
      ),
      AlphabetSection(
        title: 'T sounds',
        letters: [
          LetterSound(
            letter: 'た',
            name: 'ta',
            ipa: '/ta/',
            soundHint: 'Like "ta" in "tall"',
            example: 'たべる',
            exampleMeaning: 'to eat',
          ),
          LetterSound(
            letter: 'ち',
            name: 'chi',
            ipa: '/tɕi/',
            soundHint: 'Like "chee" — not "ti"',
            example: 'ちいさい',
            exampleMeaning: 'small',
            note: 'Irregular.',
          ),
          LetterSound(
            letter: 'つ',
            name: 'tsu',
            ipa: '/tsɯ/',
            soundHint: 'Like the "ts" in "cats" plus "u"',
            example: 'つくる',
            exampleMeaning: 'to make',
            note: 'Irregular, and hard for English speakers.',
          ),
          LetterSound(
            letter: 'て',
            name: 'te',
            ipa: '/te/',
            soundHint: 'Like "te" in "ten"',
            example: 'て',
            exampleMeaning: 'hand',
          ),
          LetterSound(
            letter: 'と',
            name: 'to',
            ipa: '/to/',
            soundHint: 'Like "toe"',
            example: 'とり',
            exampleMeaning: 'bird',
          ),
        ],
      ),
      AlphabetSection(
        title: 'N sounds',
        letters: [
          LetterSound(
            letter: 'な',
            name: 'na',
            ipa: '/na/',
            soundHint: 'Like "na" in "nah"',
            example: 'なつ',
            exampleMeaning: 'summer',
          ),
          LetterSound(
            letter: 'に',
            name: 'ni',
            ipa: '/ni/',
            soundHint: 'Like "knee"',
            example: 'にく',
            exampleMeaning: 'meat',
          ),
          LetterSound(
            letter: 'ぬ',
            name: 'nu',
            ipa: '/nɯ/',
            soundHint: 'Like "new"',
            example: 'ぬの',
            exampleMeaning: 'cloth',
          ),
          LetterSound(
            letter: 'ね',
            name: 'ne',
            ipa: '/ne/',
            soundHint: 'Like "ne" in "net"',
            example: 'ねこ',
            exampleMeaning: 'cat',
          ),
          LetterSound(
            letter: 'の',
            name: 'no',
            ipa: '/no/',
            soundHint: 'Like "no"',
            example: 'のむ',
            exampleMeaning: 'to drink',
          ),
        ],
      ),
      AlphabetSection(
        title: 'H sounds',
        letters: [
          LetterSound(
            letter: 'は',
            name: 'ha',
            ipa: '/ha/',
            soundHint: 'Like "ha"',
            example: 'はな',
            exampleMeaning: 'flower',
            note: 'Pronounced "wa" when used as a topic particle.',
          ),
          LetterSound(
            letter: 'ひ',
            name: 'hi',
            ipa: '/çi/',
            soundHint: 'Like "he"',
            example: 'ひと',
            exampleMeaning: 'person',
          ),
          LetterSound(
            letter: 'ふ',
            name: 'fu',
            ipa: '/ɸɯ/',
            soundHint: 'Between "who" and "foo" — blow gently',
            example: 'ふゆ',
            exampleMeaning: 'winter',
            note: 'Irregular.',
          ),
          LetterSound(
            letter: 'へ',
            name: 'he',
            ipa: '/he/',
            soundHint: 'Like "he" in "hen"',
            example: 'へや',
            exampleMeaning: 'room',
          ),
          LetterSound(
            letter: 'ほ',
            name: 'ho',
            ipa: '/ho/',
            soundHint: 'Like "ho"',
            example: 'ほし',
            exampleMeaning: 'star',
          ),
        ],
      ),
      AlphabetSection(
        title: 'M, Y, R, W and N',
        letters: [
          LetterSound(
            letter: 'ま',
            name: 'ma',
            ipa: '/ma/',
            soundHint: 'Like "ma"',
            example: 'まち',
            exampleMeaning: 'town',
          ),
          LetterSound(
            letter: 'み',
            name: 'mi',
            ipa: '/mi/',
            soundHint: 'Like "me"',
            example: 'みず',
            exampleMeaning: 'water',
          ),
          LetterSound(
            letter: 'む',
            name: 'mu',
            ipa: '/mɯ/',
            soundHint: 'Like "moo"',
            example: 'むし',
            exampleMeaning: 'insect',
          ),
          LetterSound(
            letter: 'め',
            name: 'me',
            ipa: '/me/',
            soundHint: 'Like "me" in "met"',
            example: 'め',
            exampleMeaning: 'eye',
          ),
          LetterSound(
            letter: 'も',
            name: 'mo',
            ipa: '/mo/',
            soundHint: 'Like "mo"',
            example: 'もり',
            exampleMeaning: 'forest',
          ),
          LetterSound(
            letter: 'や',
            name: 'ya',
            ipa: '/ja/',
            soundHint: 'Like "ya"',
            example: 'やま',
            exampleMeaning: 'mountain',
          ),
          LetterSound(
            letter: 'ゆ',
            name: 'yu',
            ipa: '/jɯ/',
            soundHint: 'Like "you"',
            example: 'ゆき',
            exampleMeaning: 'snow',
          ),
          LetterSound(
            letter: 'よ',
            name: 'yo',
            ipa: '/jo/',
            soundHint: 'Like "yo"',
            example: 'よる',
            exampleMeaning: 'night',
          ),
          LetterSound(
            letter: 'ら',
            name: 'ra',
            ipa: '/ɾa/',
            soundHint: 'Between "r" and "l" — a light tap',
            example: 'らく',
            exampleMeaning: 'comfort',
          ),
          LetterSound(
            letter: 'り',
            name: 'ri',
            ipa: '/ɾi/',
            soundHint: 'A tapped "ri"',
            example: 'りんご',
            exampleMeaning: 'apple',
          ),
          LetterSound(
            letter: 'る',
            name: 'ru',
            ipa: '/ɾɯ/',
            soundHint: 'A tapped "ru"',
            example: 'るす',
            exampleMeaning: 'absence',
          ),
          LetterSound(
            letter: 'れ',
            name: 're',
            ipa: '/ɾe/',
            soundHint: 'A tapped "re"',
            example: 'れきし',
            exampleMeaning: 'history',
          ),
          LetterSound(
            letter: 'ろ',
            name: 'ro',
            ipa: '/ɾo/',
            soundHint: 'A tapped "ro"',
            example: 'ろく',
            exampleMeaning: 'six',
          ),
          LetterSound(
            letter: 'わ',
            name: 'wa',
            ipa: '/wa/',
            soundHint: 'Like "wa" in "water"',
            example: 'わたし',
            exampleMeaning: 'I',
          ),
          LetterSound(
            letter: 'を',
            name: 'wo',
            ipa: '/o/',
            soundHint: 'Pronounced "o"',
            example: 'を',
            exampleMeaning: 'object marker',
            note: 'Only ever used as a grammatical particle.',
          ),
          LetterSound(
            letter: 'ん',
            name: 'n',
            ipa: '/ɴ/',
            soundHint: 'A standalone "n" — the only consonant on its own',
            example: 'ほん',
            exampleMeaning: 'book',
          ),
        ],
      ),
    ],
  );

  // ---------------------------------------------------------------- Chinese

  static const Alphabet _chinese = Alphabet(
    languageCode: 'zh-CN',
    note: 'Chinese is written in characters, not letters. Pinyin spells their '
        'sounds in the Latin alphabet — but the letters do not always sound '
        'the way English suggests. Tone changes meaning: the same syllable '
        'said four ways is four different words.',
    sections: [
      AlphabetSection(
        title: 'The four tones',
        subtitle: 'Learn these first — they carry meaning, not just melody.',
        letters: [
          LetterSound(
            letter: 'mā',
            name: 'mā',
            ipa: '/ma˥/',
            soundHint: 'First tone: high and flat, like holding a note',
            example: '妈',
            exampleMeaning: 'mother',
          ),
          LetterSound(
            letter: 'má',
            name: 'má',
            ipa: '/ma˧˥/',
            soundHint: 'Second tone: rising, like asking "huh?"',
            example: '麻',
            exampleMeaning: 'hemp',
          ),
          LetterSound(
            letter: 'mǎ',
            name: 'mǎ',
            ipa: '/ma˨˩˦/',
            soundHint: 'Third tone: dips down, then rises',
            example: '马',
            exampleMeaning: 'horse',
          ),
          LetterSound(
            letter: 'mà',
            name: 'mà',
            ipa: '/ma˥˩/',
            soundHint: 'Fourth tone: sharp fall, like a command',
            example: '骂',
            exampleMeaning: 'to scold',
          ),
        ],
      ),
      AlphabetSection(
        title: 'Tricky consonants',
        subtitle: 'These pinyin letters do not sound like their English '
            'counterparts.',
        letters: [
          LetterSound(
            letter: 'c',
            name: 'c',
            ipa: '/tsʰ/',
            soundHint: 'Like "ts" in "cats" — never like "k" or "s"',
            example: '菜',
            exampleMeaning: 'vegetable (cài)',
          ),
          LetterSound(
            letter: 'q',
            name: 'q',
            ipa: '/tɕʰ/',
            soundHint: 'Like "ch" in "cheese", tongue forward',
            example: '七',
            exampleMeaning: 'seven (qī)',
          ),
          LetterSound(
            letter: 'x',
            name: 'x',
            ipa: '/ɕ/',
            soundHint: 'Like "sh" in "sheep", tongue forward',
            example: '谢',
            exampleMeaning: 'thanks (xiè)',
          ),
          LetterSound(
            letter: 'z',
            name: 'z',
            ipa: '/ts/',
            soundHint: 'Like "ds" in "beds"',
            example: '子',
            exampleMeaning: 'child (zǐ)',
          ),
          LetterSound(
            letter: 'zh',
            name: 'zh',
            ipa: '/ʈʂ/',
            soundHint: 'Like "j" in "jump", tongue curled back',
            example: '中',
            exampleMeaning: 'middle (zhōng)',
          ),
          LetterSound(
            letter: 'ch',
            name: 'ch',
            ipa: '/ʈʂʰ/',
            soundHint: 'Like "ch" in "church", tongue curled back',
            example: '吃',
            exampleMeaning: 'to eat (chī)',
          ),
          LetterSound(
            letter: 'sh',
            name: 'sh',
            ipa: '/ʂ/',
            soundHint: 'Like "sh" in "shoe", tongue curled back',
            example: '是',
            exampleMeaning: 'to be (shì)',
          ),
          LetterSound(
            letter: 'r',
            name: 'r',
            ipa: '/ʐ/',
            soundHint: 'Between "r" and the "s" in "measure"',
            example: '人',
            exampleMeaning: 'person (rén)',
          ),
        ],
      ),
      AlphabetSection(
        title: 'Vowels',
        letters: [
          LetterSound(
            letter: 'a',
            name: 'a',
            ipa: '/a/',
            soundHint: 'Like "a" in "father"',
            example: '八',
            exampleMeaning: 'eight (bā)',
          ),
          LetterSound(
            letter: 'o',
            name: 'o',
            ipa: '/o/',
            soundHint: 'Like "o" in "more"',
            example: '我',
            exampleMeaning: 'I (wǒ)',
          ),
          LetterSound(
            letter: 'e',
            name: 'e',
            ipa: '/ɤ/',
            soundHint: 'Like "u" in "duh"',
            example: '饿',
            exampleMeaning: 'hungry (è)',
          ),
          LetterSound(
            letter: 'i',
            name: 'i',
            ipa: '/i/',
            soundHint: 'Like "ee" in "see"',
            example: '一',
            exampleMeaning: 'one (yī)',
          ),
          LetterSound(
            letter: 'u',
            name: 'u',
            ipa: '/u/',
            soundHint: 'Like "oo" in "moon"',
            example: '五',
            exampleMeaning: 'five (wǔ)',
          ),
          LetterSound(
            letter: 'ü',
            name: 'ü',
            ipa: '/y/',
            soundHint: 'Say "ee" with rounded lips',
            example: '女',
            exampleMeaning: 'woman (nǚ)',
            note: 'No English equivalent.',
          ),
        ],
      ),
    ],
  );
}

enum _SpanishDialect { peninsular, latam }
